/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as protectedRecipeIndexRouteImport } from './routes/(protected)/recipe/index'
import { Route as protectedProfileIndexRouteImport } from './routes/(protected)/profile/index'
import { Route as protectedNotificationIndexRouteImport } from './routes/(protected)/notification/index'
import { Route as protectedIngredientsIndexRouteImport } from './routes/(protected)/ingredients/index'
import { Route as protectedHomeIndexRouteImport } from './routes/(protected)/home/index'
import { Route as authAuthCallbackRouteImport } from './routes/(auth)/auth/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedRecipeIndexRoute = protectedRecipeIndexRouteImport.update({
  id: '/(protected)/recipe/',
  path: '/recipe/',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedProfileIndexRoute = protectedProfileIndexRouteImport.update({
  id: '/(protected)/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedNotificationIndexRoute =
  protectedNotificationIndexRouteImport.update({
    id: '/(protected)/notification/',
    path: '/notification/',
    getParentRoute: () => rootRouteImport,
  } as any)
const protectedIngredientsIndexRoute =
  protectedIngredientsIndexRouteImport.update({
    id: '/(protected)/ingredients/',
    path: '/ingredients/',
    getParentRoute: () => rootRouteImport,
  } as any)
const protectedHomeIndexRoute = protectedHomeIndexRouteImport.update({
  id: '/(protected)/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthCallbackRoute = authAuthCallbackRouteImport.update({
  id: '/(auth)/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/auth/callback': typeof authAuthCallbackRoute
  '/home': typeof protectedHomeIndexRoute
  '/ingredients': typeof protectedIngredientsIndexRoute
  '/notification': typeof protectedNotificationIndexRoute
  '/profile': typeof protectedProfileIndexRoute
  '/recipe': typeof protectedRecipeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/auth/callback': typeof authAuthCallbackRoute
  '/home': typeof protectedHomeIndexRoute
  '/ingredients': typeof protectedIngredientsIndexRoute
  '/notification': typeof protectedNotificationIndexRoute
  '/profile': typeof protectedProfileIndexRoute
  '/recipe': typeof protectedRecipeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(auth)/auth/callback': typeof authAuthCallbackRoute
  '/(protected)/home/': typeof protectedHomeIndexRoute
  '/(protected)/ingredients/': typeof protectedIngredientsIndexRoute
  '/(protected)/notification/': typeof protectedNotificationIndexRoute
  '/(protected)/profile/': typeof protectedProfileIndexRoute
  '/(protected)/recipe/': typeof protectedRecipeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/auth/callback'
    | '/home'
    | '/ingredients'
    | '/notification'
    | '/profile'
    | '/recipe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/auth/callback'
    | '/home'
    | '/ingredients'
    | '/notification'
    | '/profile'
    | '/recipe'
  id:
    | '__root__'
    | '/'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(auth)/auth/callback'
    | '/(protected)/home/'
    | '/(protected)/ingredients/'
    | '/(protected)/notification/'
    | '/(protected)/profile/'
    | '/(protected)/recipe/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
  authAuthCallbackRoute: typeof authAuthCallbackRoute
  protectedHomeIndexRoute: typeof protectedHomeIndexRoute
  protectedIngredientsIndexRoute: typeof protectedIngredientsIndexRoute
  protectedNotificationIndexRoute: typeof protectedNotificationIndexRoute
  protectedProfileIndexRoute: typeof protectedProfileIndexRoute
  protectedRecipeIndexRoute: typeof protectedRecipeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/recipe/': {
      id: '/(protected)/recipe/'
      path: '/recipe'
      fullPath: '/recipe'
      preLoaderRoute: typeof protectedRecipeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/profile/': {
      id: '/(protected)/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof protectedProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/notification/': {
      id: '/(protected)/notification/'
      path: '/notification'
      fullPath: '/notification'
      preLoaderRoute: typeof protectedNotificationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/ingredients/': {
      id: '/(protected)/ingredients/'
      path: '/ingredients'
      fullPath: '/ingredients'
      preLoaderRoute: typeof protectedIngredientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/home/': {
      id: '/(protected)/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof protectedHomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth/callback': {
      id: '/(auth)/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof authAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
  authAuthCallbackRoute: authAuthCallbackRoute,
  protectedHomeIndexRoute: protectedHomeIndexRoute,
  protectedIngredientsIndexRoute: protectedIngredientsIndexRoute,
  protectedNotificationIndexRoute: protectedNotificationIndexRoute,
  protectedProfileIndexRoute: protectedProfileIndexRoute,
  protectedRecipeIndexRoute: protectedRecipeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
